# Initial idea of repoman checks: https://github.com/mrueg/repoman-travis

sudo: false
language: python
python:
    - pypy

git:
    depth: 1

env:
    global:
        - PORTAGE_ROOT="$(mktemp -d)"
    matrix:
        - PORTAGE_VER="2.2.24"
        - PORTAGE_VER="2.2.26"
        - PORTAGE_VER="2.2.27"
        - PORTAGE_VER="2.2.28"

matrix:
    allow_failures:
        - env: PORTAGE_VER="2.2.24"
    fast_finish: true


install:
    - tools/install_portage.sh
    - export PATH="${PORTAGE_ROOT}/usr/bin:${PATH}"
    - export PORTAGE_CONFIGROOT="${PORTAGE_ROOT}" ROOT="${PORTAGE_ROOT}"

script:
    - repoman full -d


notifications:
    email:
        on_failure: change
