# Based on https://github.com/mrueg/repoman-travis

sudo: false
language: python
python:
    - pypy

env:
    global:
        - PORTAGE_ROOT="$(mktemp -d)"
    matrix:
        - PORTAGE_VER="2.2.26"
        - PORTAGE_VER="2.2.27"
        - PORTAGE_VER="2.2.28"


install:
    - tools/install_portage.sh
    - export PATH="${PORTAGE_ROOT}/usr/bin:${PATH}"
    - export PORTAGE_CONFIGROOT="${PORTAGE_ROOT}" ROOT="${PORTAGE_ROOT}"

script:
    - repoman full -d

after_success:
    - repoman manifest
    - git status


notifications:
    email:
        on_failure: change
