# Based on https://github.com/mrueg/repoman-travis

sudo: false
language: python
python:
    - pypy

env:
    global:
        - PORTAGE_ROOT="$(mktemp -d)"
    matrix:
        - PORTAGE_VER="2.2.27"

install:
    - tools/install_portage.sh
    - export PATH="${PORTAGE_ROOT}/usr/bin:${PATH}"
    - export PYTHONPATH="${PORTAGE_ROOT}/usr/lib64/pypy/site-packages:${PYTHONPATH}"

script:
    - repoman full -d

notifications:
    email:
        on_failure: change
