# Initial idea of repoman checks: https://github.com/mrueg/repoman-travis

sudo: false
language: python
python:
    - "3.4"

git:
    depth: 1
branches:
    only:
        - master
        - dev
        - /^ci\//

env:
    global:
        ## configurable variables
        - OVERLAY_NAME='rindeal'
    matrix:
#        - PORTAGE_VER="2.2.26"
        - PORTAGE_VER="2.2.28"

matrix:
    fast_finish: true


install:
    - wget https://github.com/rindeal/travis-ci-for-gentoo-overlays/raw/master/src/source.sh -O /tmp/tcifgo.sh
    - . /tmp/tcifgo.sh

script:
    - repoman full -d

# after_success:
#     - cd "${TRAVIS_BUILD_DIR}"
#     - git config user.name "Travis CI"
#     - git config user.email "Travis@CI"
#     - git reset --hard $TRAVIS_COMMIT


notifications:
    email:
        on_success: never
        on_failure: change
