# Initial idea of repoman checks: https://github.com/mrueg/repoman-travis

sudo: false
language: python
python:
    - "3.4"

git:
    depth: 1
branches:
    only:
        - master
        - dev
        - /^mr-.*$/

env:
    global:
        - PORTAGE_ROOT="$(mktemp -d)"
    matrix:
        - PORTAGE_VER="2.2.26"
        - PORTAGE_VER="2.2.28"

matrix:
    fast_finish: true


install:
    - .travis/install_portage.sh
    - export PATH="${PORTAGE_ROOT}/usr/bin:${PATH}"
    - export PORTAGE_CONFIGROOT="${PORTAGE_ROOT}" ROOT="${PORTAGE_ROOT}"

script:
    - repoman full -d


notifications:
    email:
        on_success: never
        on_failure: change
